if has("macunix")
    " This is needed to disable the highlights of matching "{( etc...
	function! g:FckThatMatchParen ()
		if exists(":NoMatchParen")
			:NoMatchParen
		endif
	endfunction

	augroup plugin_initialize
		autocmd!
		autocmd VimEnter * call FckThatMatchParen()
	augroup END
elseif has("unix")
    let g:system_copy#copy_command = $VIMCLIP
endif

" python3 from powerline.vim import setup as powerline_setup
" python3 powerline_setup()
" python3 del powerline_setup 

set path+=**                                " Files from all subfolders will tabcomplete
set wildmenu                                " Display all matching file when tabcomplete
set nocompatible                            " Disable vi compatibility (might be superfluous)
set autoread                                " Auto reload changed files
set laststatus=2                            " status bar at the bottom
set t_Co=256                                " Color settings
syntax enable                               " syntax highligh
set number                                  " show line numbers
set relativenumber                          " relative numbers are shown
set ts=4                                    " set tabs to have 4 spaces
set autoindent                              " indent when moving to the next line while writing code
set expandtab                               " expand tabs into spaces
set shiftwidth=4                            " when using the >> or << commands, shift lines by 4 spaces
set cursorline                              " show a visual line under the cursor's current line
set noshowmatch                             " Do not show the matching part of the pair for [] {} and ()
set splitright                              " Open new splits to the right
set splitbelow                              " Open new splits to the bottom
set history=1000                            " Set remembered lines
set hlsearch                                " Highligh searches
set incsearch                               " Show search results as you type
set timeoutlen=1000 ttimeoutlen=0           " Remove timeout when hitting escape
set list
set listchars=tab:>-,eol:$,space:.,trail:x
" set backspace=indent,eol,start              " http://vi.stackexchange.com/a/2163

" Python specific stuff
let python_highlight_all = 1                " enable all Python syntax highlighting features
set foldlevel=99
au BufNewFile,BufRead *.py
    \set tabstop=4
    \set softtabstop=4
    \set textwidth=79
    \set fileformat=unix
    \set foldmethod=indent
    \match BadWhitespace /\s\+$/
    \set encoding=utf-8

au BufNewFile,BufRead *.py noremap <Leader>l :call VimuxRunCommand("pylint " . bufname("%"))<CR>
au BufNewFile,BufRead *.py noremap <Leader>t :call VimuxRunCommand("pytest")<CR>

if $VIRTUAL_ENV != ""
    au BufNewFile,BufRead *.py noremap <Leader>p :call VimuxRunCommand($VIRTUAL_ENV . "/bin/python " . bufname("%"))<CR>
else
    au BufNewFile,BufRead *.py noremap <Leader>p :call VimuxRunCommand("python " . bufname("%"))<CR>
endif

" Go specific stuff
let g:go_fmt_command = "goimports"          " Autoimport on save
autocmd BufNewFile,BufRead *.go set foldmethod=syntax           " Set folding to syntax if it's a go file
autocmd BufNewFile,BufRead *.go noremap <C-a> :GoAlternate<CR>
" autocmd BufNewFile,BufRead *.go noremap <C-d> :GoDoc<CR> " Go docs
autocmd BufNewFile,BufRead *.go noremap <C-r> :GoRename<CR>
autocmd BufNewFile,BufRead *.go noremap <C-c> :GoCoverage<CR>
autocmd BufNewFile,BufRead *.go noremap <C-i> :GoInfo<CR>
autocmd BufNewFile,BufRead *.go noremap <Leader>t :GoTest<CR>
autocmd BufNewFile,BufRead *.go noremap <Leader>l :GoMetaLinter<CR>
autocmd BufNewFile,BufRead *.go noremap <Leader>f :GoTestFunc<CR>
autocmd BufNewFile,BufRead *.go noremap <Leader>r :GoRun<CR>

" JS
autocmd BufNewFile,BufRead *.js set ts=2

" Shortcuts
" quite all with leader q
map <Leader>q :qall<CR>                     " Quit all with Leader+q
nnoremap <C-h> <C-w>h                       " Moving between panes on split screen
nnoremap <C-j> <C-w>j                       " Moving between panes on split screen
nnoremap <C-k> <C-w>k                       " Moving between panes on split screen
nnoremap <C-l> <C-w>l                       " Moving between panes on split screen
nnoremap <space> za                         " fold with space
noremap <Leader>x :call VimuxCloseRunner()<CR>
" Copy to unnamed register
noremap <Leader>d "_
" Toogle NerdTree
map <C-n> :NERDTreeToggle<CR>

" Get off my lawn - helpful when learning Vim :)
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>


" YcmSettings
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>
nmap <C-f> <plug>(YCMHover)
let g:ycm_autoclose_preview_window_after_completion=1


source ~/.vim/plugins.vim
source ~/.vim/statusline.vim


colo gruvbox
set background=dark
" colo molokai
" let g:molokai_original = 1
hi StatusLineTerm ctermbg=24 ctermfg=254

" VIMux
let g:VimuxOrientation = "h"
let g:VimuxHeight = "50"

let g:prettier#config#single_quote = 'true'
let g:prettier#config#trailing_comma = 'all'


"python with virtualenv support

py3 << EOF
import os
import sys
if 'VIRTUAL_ENV' in os.environ:
  project_base_dir = os.environ['VIRTUAL_ENV']
  activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
  exec(open(activate_this).read(), dict(__file__=activate_this))
EOF
